### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by mehmoodakhter5** [kudashevs/laravel-share-buttons#7]
Hello,
Instagram button should be in the list.
Thanks

**Comment by kudashevs** [comment]
Hello @mehmoodakhter5,

As I know, Instagram doesn't provide any web-sharing endpoints.
If you know any ways to share web links on Instagram please let me know.

**Comment by kudashevs** [comment]
I close the issue for now.

@mehmoodakhter5 if you have any information on how to implement Instagram share web links, feel free to reopen it.
