### ISSUE TITLE
bug: facebook not work

### ISSUE THREAD

**Issue by mohssineAboutaj** [kudashevs/laravel-share-buttons#9]
I'm using the `getRawLinks()` to get social share links, like this:
```php
$shareLinks = ShareButtons::currentPage($title)->facebook()->twitter()->telegram()->whatsapp()->getRawLinks();
```
The other platforms works fine but when I click on the **Facebook** link it redirect me to this [link](https://www.facebook.com/share_channel/) 
![image](https://github.com/kudashevs/laravel-share-buttons/assets/30943833/527738fa-f1f6-4200-8e61-2216817a3505)

**Comment by kudashevs** [comment]
@mohssineAboutaj Could you please provide the link that was generated? I mean before the redirect?

It seems that `facebook` checks the provided link to have a valid domain.
And if it doesn't have a valid domain name in it, it shows this error.

**Comment by kudashevs** [comment]
I'm going to close the issue. @mohssineAboutaj feel free to reopen it when you are ready to provide additional information.

**Comment by mohssineAboutaj** [comment]
It was a `localhost` domain, i guess that is the problem
Thank you so much
